export const newValue = {
    "users_id": 1,
    "name": "钻石啊",
    "categories_id": 1,
    "quality": 1.5,
    "length": 0.1,
    "width": 0.2,
    "height": 0.3,
    "carving": "雕刻",
    "definition": "术语与定义",
    "age_place": "年代与产地",
    "mineral_structure": "主要矿物组成",
    "chemical_structure": "主要化学组成",
    "exterior": "外观描述",
    "color": "颜色",
    "luster": "光泽",
    "transparency": "透明度",
    "cleavage": "解理",
    "optical": "光性特征",
    "mohs": "摩氏硬度",
    "density": "密度",
    "refraction": "折射率",
    "fluorescence": "荧光观察",
    "infrared": "红外光谱",
    "microscopic": "显微结构",
    "special_optical": "特殊光学效应",
    "chemical_properties": "化学性质",
    "color_element": "主要色诱导元素",
    "crystal_system": "晶系",
    "proportion": "比重",
    "hardness": "硬度",
    "critical_angle": "临界角度",
    "cutting_angle": "切磨角度",
    "refolding": "重折率",
    "dispersion": "色散",
    "proportion_extent": "比重幅度",
    "others": {
        "others_info_key1": "wdnb",
        "others_info_key2": "wdexnb"
    },
    "picture_url": [
        "http://cdn.elatis.cn/archives/313/66613251_p0_2.png",
        "http://cdn.elatis.cn/archives/271/56866134_p0.jpg"
    ],
    "third_valuation": 19000.5,
    "holder_valuation": 35000.5,
    "system_valuation": 20000.5,
    "cert_report_picture": [
        "http://cdn.elatis.cn/archives/313/66613251_p0_2.png",
        "http://cdn.elatis.cn/archives/271/56866134_p0.jpg"
    ],
    "cert_body": "鉴定机构",
    "cert_date": "2019-09-15",
    "cert_examiner": "鉴定人"
}

